### ISSUE TITLE
trinity.so 저장소 알리기

### ISSUE THREAD

**Issue by eces** [eces/trinity.so#3]
To: @AiOO  @kanghyojun 
최근 trinity.so 내용

**Comment by AiOO** [comment]
@eces 이거 @trinitystudiokr 오거나이제이션으로 옮겨주실 수 있나여 ㅋㅋㅋ

**Comment by eces** [comment]
> @eces 이거 @trinitystudiokr 오거나이제이션으로 옮겨주실 수 있나여 ㅋㅋㅋ

내용 참고용으로 일단 옮겼습니다. 옮기긴 했는데 너무 오래전에 만든거라 새로운 스택으로 바꾸는게 좋아보여요.

**Comment by AiOO** [comment]
:+1: 이전했으니 이 이슈는 클로즈..
